# Per-database configuration: versions, years, systems, satellite accounts
# (with GWP factors used to aggregate to a single "GHG" indicator) and the
# electricity sector/commodity labels to keep in the final emission factors.

properties = {
    'exiobase_monetary_iot': {
        'name': 'EXIOBASE',
        'table': 'IOT',
        'versions': ['3.10.2'],
        'systems': ['ixi', 'pxp'],
        'years': [2023, 2022, 2017],
        'gwps': {
            'CO2 - combustion - air': 1.0,
            'CH4 - combustion - air': 29.7,
            'N2O - combustion - air': 264.8,
            'HFC - air': 1,
            'SF6 - air': 23506,
            'CO - combustion - air': 4.1,
        },
        'labels_list': {
            'aggr': {
                'ixi': [
                    'Production T&D of electricity',
                ],
                'pxp': [
                    'Electricity & transmission',
                ],
            },
            'non_aggr': {
                'ixi': [
                    'Production of electricity by coal',
                    'Production of electricity by gas',
                    'Production of electricity by nuclear',
                    'Production of electricity by hydro',
                    'Production of electricity by wind',
                    'Production of electricity by petroleum and other oil derivatives',
                    'Production of electricity by biomass and waste',
                    'Production of electricity by solar photovoltaic',
                    'Production of electricity by solar thermal',
                    'Production of electricity by tide, wave, ocean',
                    'Production of electricity by Geothermal',
                    'Production of electricity nec',
                ],
                'pxp': [
                    'Electricity by coal',
                    'Electricity by gas',
                    'Electricity by nuclear',
                    'Electricity by hydro',
                    'Electricity by wind',
                    'Electricity by petroleum and other oil derivatives',
                    'Electricity by biomass and waste',
                    'Electricity by solar photovoltaic',
                    'Electricity by solar thermal',
                    'Electricity by tide, wave, ocean',
                    'Electricity by Geothermal',
                ],
            },
        },
    },

    'eora26': {
        'name': 'EORA26',
        'table': 'IOT',
        'versions': ['199.82'],         # autodetected by mario.parse_eora
        'years': [2017],
        'gwps': {
            'I-GHG-CO2 emissions (Gg) - Public electricity and heat production': 1,
            'I-GHG-CO2 emissions (Gg) - Other Energy Industries': 1,
            'I-GHG-CO2 emissions (Gg) - Manufacturing Industries and Construction': 1,
            'I-GHG-CO2 emissions (Gg) - Domestic aviation': 1,
            'I-GHG-CO2 emissions (Gg) - Road transportation': 1,
            'I-GHG-CO2 emissions (Gg) - Rail transportation': 1,
            'I-GHG-CO2 emissions (Gg) - Inland navigation': 1,
            'I-GHG-CO2 emissions (Gg) - Other transportation': 1,
            'I-GHG-CO2 emissions (Gg) - Residential and other sectors': 1,
            'I-GHG-CO2 emissions (Gg) - Fugitive emissions from solid fuels': 1,
            'I-GHG-CO2 emissions (Gg) - Fugitive emissions from oil and gas': 1,
            'I-GHG-CO2 emissions (Gg) - Memo: International aviation': 1,
            'I-GHG-CO2 emissions (Gg) - Memo: International navigation': 1,
            'I-GHG-CO2 emissions (Gg) - Production of minerals': 1,
            'I-GHG-CO2 emissions (Gg) - Cement production': 1,
            'I-GHG-CO2 emissions (Gg) - Lime production': 1,
            'I-GHG-CO2 emissions (Gg) - Production of chemicals': 1,
            'I-GHG-CO2 emissions (Gg) - Production of metals': 1,
            'I-GHG-CO2 emissions (Gg) - Production of pulp/paper/food/drink': 1,
            'I-GHG-CO2 emissions (Gg) - Production of halocarbons and SF6': 1,
            'I-GHG-CO2 emissions (Gg) - Refrigeration and Air Conditioning': 1,
            'I-GHG-CO2 emissions (Gg) - Foam Blowing': 1,
            'I-GHG-CO2 emissions (Gg) - Fire Extinguishers': 1,
            'I-GHG-CO2 emissions (Gg) - Aerosols': 1,
            'I-GHG-CO2 emissions (Gg) - F-gas as Solvent': 1,
            'I-GHG-CO2 emissions (Gg) - Semiconductor/Electronics Manufacture': 1,
            'I-GHG-CO2 emissions (Gg) - Electrical Equipment': 1,
            'I-GHG-CO2 emissions (Gg) - Other F-gas use': 1,
            'I-GHG-CO2 emissions (Gg) - Non-energy use of lubricants/waxes (CO2)': 1,
            'I-GHG-CO2 emissions (Gg) - Solvent and other product use: paint': 1,
            'I-GHG-CO2 emissions (Gg) - Solvent and other product use: degrease': 1,
            'I-GHG-CO2 emissions (Gg) - Solvent and other product use: chemicals': 1,
            'I-GHG-CO2 emissions (Gg) - Solvent and other product use: other': 1,
            'I-GHG-CO2 emissions (Gg) - Enteric fermentation': 1,
            'I-GHG-CO2 emissions (Gg) - Manure management': 1,
            'I-GHG-CO2 emissions (Gg) - Rice cultivation': 1,
            'I-GHG-CO2 emissions (Gg) - Direct soil emissions': 1,
            'I-GHG-CO2 emissions (Gg) - Manure in pasture/range/paddock': 1,
            'I-GHG-CO2 emissions (Gg) - Indirect N2O from agriculture': 1,
            'I-GHG-CO2 emissions (Gg) - Other direct soil emissions': 1,
            'I-GHG-CO2 emissions (Gg) - Savanna burning': 1,
            'I-GHG-CO2 emissions (Gg) - Agricultural waste burning': 1,
            'I-GHG-CO2 emissions (Gg) - Forest fires': 1,
            'I-GHG-CO2 emissions (Gg) - Grassland fires': 1,
            'I-GHG-CO2 emissions (Gg) - Decay of wetlands/peatlands': 1,
            'I-GHG-CO2 emissions (Gg) - Other vegetation fires': 1,
            'I-GHG-CO2 emissions (Gg) - Forest Fires-Post burn decay': 1,
            'I-GHG-CO2 emissions (Gg) - Solid waste disposal on land': 1,
            'I-GHG-CO2 emissions (Gg) - Wastewater handling': 1,
            'I-GHG-CO2 emissions (Gg) - Waste incineration': 1,
            'I-GHG-CO2 emissions (Gg) - Other waste handling': 1,
            'I-GHG-CO2 emissions (Gg) - Fossil fuel fires': 1,
            'I-GHG-CO2 emissions (Gg) - Indirect N2O from non-agricultural NOx': 1,
            'I-GHG-CO2 emissions (Gg) - Indirect N2O from non-agricultural NH3': 1,
            'I-GHG-CO2 emissions (Gg) - Other sources': 1.0,
            'I-GHG-CH4 emissions (Gg) - Public electricity and heat production': 29.7,
            'I-GHG-CH4 emissions (Gg) - Other Energy Industries': 29.7,
            'I-GHG-CH4 emissions (Gg) - Manufacturing Industries and Construction': 29.7,
            'I-GHG-CH4 emissions (Gg) - Domestic aviation': 29.7,
            'I-GHG-CH4 emissions (Gg) - Road transportation': 29.7,
            'I-GHG-CH4 emissions (Gg) - Rail transportation': 29.7,
            'I-GHG-CH4 emissions (Gg) - Inland navigation': 29.7,
            'I-GHG-CH4 emissions (Gg) - Other transportation': 29.7,
            'I-GHG-CH4 emissions (Gg) - Residential and other sectors': 29.7,
            'I-GHG-CH4 emissions (Gg) - Fugitive emissions from solid fuels': 29.7,
            'I-GHG-CH4 emissions (Gg) - Fugitive emissions from oil and gas': 29.7,
            'I-GHG-CH4 emissions (Gg) - Memo: International aviation': 29.7,
            'I-GHG-CH4 emissions (Gg) - Memo: International navigation': 29.7,
            'I-GHG-CH4 emissions (Gg) - Production of minerals': 29.7,
            'I-GHG-CH4 emissions (Gg) - Cement production': 29.7,
            'I-GHG-CH4 emissions (Gg) - Lime production': 29.7,
            'I-GHG-CH4 emissions (Gg) - Production of chemicals': 29.7,
            'I-GHG-CH4 emissions (Gg) - Production of metals': 29.7,
            'I-GHG-CH4 emissions (Gg) - Production of pulp/paper/food/drink': 29.7,
            'I-GHG-CH4 emissions (Gg) - Production of halocarbons and SF6': 29.7,
            'I-GHG-CH4 emissions (Gg) - Refrigeration and Air Conditioning': 29.7,
            'I-GHG-CH4 emissions (Gg) - Foam Blowing': 29.7,
            'I-GHG-CH4 emissions (Gg) - Fire Extinguishers': 29.7,
            'I-GHG-CH4 emissions (Gg) - Aerosols': 29.7,
            'I-GHG-CH4 emissions (Gg) - F-gas as Solvent': 29.7,
            'I-GHG-CH4 emissions (Gg) - Semiconductor/Electronics Manufacture': 29.7,
            'I-GHG-CH4 emissions (Gg) - Electrical Equipment': 29.7,
            'I-GHG-CH4 emissions (Gg) - Other F-gas use': 29.7,
            'I-GHG-CH4 emissions (Gg) - Non-energy use of lubricants/waxes (CO2)': 29.7,
            'I-GHG-CH4 emissions (Gg) - Solvent and other product use: paint': 29.7,
            'I-GHG-CH4 emissions (Gg) - Solvent and other product use: degrease': 29.7,
            'I-GHG-CH4 emissions (Gg) - Solvent and other product use: chemicals': 29.7,
            'I-GHG-CH4 emissions (Gg) - Solvent and other product use: other': 29.7,
            'I-GHG-CH4 emissions (Gg) - Enteric fermentation': 29.7,
            'I-GHG-CH4 emissions (Gg) - Manure management': 29.7,
            'I-GHG-CH4 emissions (Gg) - Rice cultivation': 29.7,
            'I-GHG-CH4 emissions (Gg) - Direct soil emissions': 29.7,
            'I-GHG-CH4 emissions (Gg) - Manure in pasture/range/paddock': 29.7,
            'I-GHG-CH4 emissions (Gg) - Indirect N2O from agriculture': 29.7,
            'I-GHG-CH4 emissions (Gg) - Other direct soil emissions': 29.7,
            'I-GHG-CH4 emissions (Gg) - Savanna burning': 29.7,
            'I-GHG-CH4 emissions (Gg) - Agricultural waste burning': 29.7,
            'I-GHG-CH4 emissions (Gg) - Forest fires': 29.7,
            'I-GHG-CH4 emissions (Gg) - Grassland fires': 29.7,
            'I-GHG-CH4 emissions (Gg) - Decay of wetlands/peatlands': 29.7,
            'I-GHG-CH4 emissions (Gg) - Other vegetation fires': 29.7,
            'I-GHG-CH4 emissions (Gg) - Forest Fires-Post burn decay': 29.7,
            'I-GHG-CH4 emissions (Gg) - Solid waste disposal on land': 29.7,
            'I-GHG-CH4 emissions (Gg) - Wastewater handling': 29.7,
            'I-GHG-CH4 emissions (Gg) - Waste incineration': 29.7,
            'I-GHG-CH4 emissions (Gg) - Other waste handling': 29.7,
            'I-GHG-CH4 emissions (Gg) - Fossil fuel fires': 29.7,
            'I-GHG-CH4 emissions (Gg) - Indirect N2O from non-agricultural NOx': 29.7,
            'I-GHG-CH4 emissions (Gg) - Indirect N2O from non-agricultural NH3': 29.7,
            'I-GHG-CH4 emissions (Gg) - Other sources': 29.7,
            'I-GHG-N2O emissions (Gg) - Public electricity and heat production': 264.8,
            'I-GHG-N2O emissions (Gg) - Other Energy Industries': 264.8,
            'I-GHG-N2O emissions (Gg) - Manufacturing Industries and Construction': 264.8,
            'I-GHG-N2O emissions (Gg) - Domestic aviation': 264.8,
            'I-GHG-N2O emissions (Gg) - Road transportation': 264.8,
            'I-GHG-N2O emissions (Gg) - Rail transportation': 264.8,
            'I-GHG-N2O emissions (Gg) - Inland navigation': 264.8,
            'I-GHG-N2O emissions (Gg) - Other transportation': 264.8,
            'I-GHG-N2O emissions (Gg) - Residential and other sectors': 264.8,
            'I-GHG-N2O emissions (Gg) - Fugitive emissions from solid fuels': 264.8,
            'I-GHG-N2O emissions (Gg) - Fugitive emissions from oil and gas': 264.8,
            'I-GHG-N2O emissions (Gg) - Memo: International aviation': 264.8,
            'I-GHG-N2O emissions (Gg) - Memo: International navigation': 264.8,
            'I-GHG-N2O emissions (Gg) - Production of minerals': 264.8,
            'I-GHG-N2O emissions (Gg) - Cement production': 264.8,
            'I-GHG-N2O emissions (Gg) - Lime production': 264.8,
            'I-GHG-N2O emissions (Gg) - Production of chemicals': 264.8,
            'I-GHG-N2O emissions (Gg) - Production of metals': 264.8,
            'I-GHG-N2O emissions (Gg) - Production of pulp/paper/food/drink': 264.8,
            'I-GHG-N2O emissions (Gg) - Production of halocarbons and SF6': 264.8,
            'I-GHG-N2O emissions (Gg) - Refrigeration and Air Conditioning': 264.8,
            'I-GHG-N2O emissions (Gg) - Foam Blowing': 264.8,
            'I-GHG-N2O emissions (Gg) - Fire Extinguishers': 264.8,
            'I-GHG-N2O emissions (Gg) - Aerosols': 264.8,
            'I-GHG-N2O emissions (Gg) - F-gas as Solvent': 264.8,
            'I-GHG-N2O emissions (Gg) - Semiconductor/Electronics Manufacture': 264.8,
            'I-GHG-N2O emissions (Gg) - Electrical Equipment': 264.8,
            'I-GHG-N2O emissions (Gg) - Other F-gas use': 264.8,
            'I-GHG-N2O emissions (Gg) - Non-energy use of lubricants/waxes (CO2)': 264.8,
            'I-GHG-N2O emissions (Gg) - Solvent and other product use: paint': 264.8,
            'I-GHG-N2O emissions (Gg) - Solvent and other product use: degrease': 264.8,
            'I-GHG-N2O emissions (Gg) - Solvent and other product use: chemicals': 264.8,
            'I-GHG-N2O emissions (Gg) - Solvent and other product use: other': 264.8,
            'I-GHG-N2O emissions (Gg) - Enteric fermentation': 264.8,
            'I-GHG-N2O emissions (Gg) - Manure management': 264.8,
            'I-GHG-N2O emissions (Gg) - Rice cultivation': 264.8,
            'I-GHG-N2O emissions (Gg) - Direct soil emissions': 264.8,
            'I-GHG-N2O emissions (Gg) - Manure in pasture/range/paddock': 264.8,
            'I-GHG-N2O emissions (Gg) - Indirect N2O from agriculture': 264.8,
            'I-GHG-N2O emissions (Gg) - Other direct soil emissions': 264.8,
            'I-GHG-N2O emissions (Gg) - Savanna burning': 264.8,
            'I-GHG-N2O emissions (Gg) - Agricultural waste burning': 264.8,
            'I-GHG-N2O emissions (Gg) - Forest fires': 264.8,
            'I-GHG-N2O emissions (Gg) - Grassland fires': 264.8,
            'I-GHG-N2O emissions (Gg) - Decay of wetlands/peatlands': 264.8,
            'I-GHG-N2O emissions (Gg) - Other vegetation fires': 264.8,
            'I-GHG-N2O emissions (Gg) - Forest Fires-Post burn decay': 264.8,
            'I-GHG-N2O emissions (Gg) - Solid waste disposal on land': 264.8,
            'I-GHG-N2O emissions (Gg) - Wastewater handling': 264.8,
            'I-GHG-N2O emissions (Gg) - Waste incineration': 264.8,
            'I-GHG-N2O emissions (Gg) - Other waste handling': 264.8,
            'I-GHG-N2O emissions (Gg) - Fossil fuel fires': 264.8,
            'I-GHG-N2O emissions (Gg) - Indirect N2O from non-agricultural NOx': 264.8,
            'I-GHG-N2O emissions (Gg) - Indirect N2O from non-agricultural NH3': 264.8,
            'I-GHG-N2O emissions (Gg) - Other sources': 264.8,
        },
        'labels_list': [
            'Electricity, Gas and Water',
        ],
    },

    'emerging_v1.0': {
        'name': 'EMERGING',
        'table': 'IOT',
        'versions': ['1.0'],
        'years': [2017],
        'gwps': {
            'Coal': 1,
            'Natural gas': 1,
            'Oil products': 1,
            'Crude, NGL, Ref Feeds.': 1,
            'Oil shale & oil sands': 1,
            'Peat & Peat products': 1,
            'Other': 1,
        },
        'labels_list': ['electricity'],
    },

    'emerging_v2.2': {
        'name': 'EMERGING',
        'table': 'IOT',
        'versions': ['2.2'],
        'years': [2018, 2023],
        'gwps': {
            'Coal': 1,
            'Natural gas': 1,
            'Oil products': 1,
            'Crude, NGL, Ref Feeds.': 1,
            'Oil shale & oil sands': 1,
            'Peat & Peat products': 1,
            'Other': 1,
        },
        'labels_list': ['electricity'],
    },

    'gloria': {
        'name': 'GLORIA',
        'table': 'SUT',
        'versions': ['0.60'],
        'years': [2017, 2023],
        'gwps': {
            "Emissions (EDGAR) | 'co2_excl_short_cycle_org_c_total_EDGAR_consistent'": 1,
            "Emissions (EDGAR) | 'ch4_total_EDGAR_consistent'": 29.7,
            "Emissions (EDGAR) | 'n2o_total_EDGAR_consistent'": 264.8,
            "Emissions (EDGAR) | 'hfc_23_total_EDGAR_consistent'": 1,
            "Emissions (EDGAR) | 'sf6_total_EDGAR_consistent'": 23506,
            "Emissions (EDGAR) | 'co_total_EDGAR_consistent'": 4.1,
        },
        'labels_list': {
            'Commodity': ['Electric power generation, transmission and distribution'],
            'Activity': ['Electric power generation, transmission and distribution'],
        },
    },

    'gtap': {
        'name': 'GTAP',
        'table': 'IOT',
        'versions': ['12.Power.MRIO'],
        'years': [2017],
        'gwps': {
            'Coal': 1,
            'Natural gas': 1,
            'Oil products': 1,
            'Crude, NGL, Ref Feeds.': 1,
            'Oil shale & oil sands': 1,
            'Peat & Peat products': 1,
            'Other': 1,
        },
        'labels_list': ['electricity'],
    },


}
